pico-scale: include/hx711_scale_adaptor.h File Reference
hx711_scale_adaptor.h File Reference
#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include "scale_adaptor.h"
#include "../extern/hx711-pico-c/include/common.h"
Data Structures
struct hx711_scale_adaptor_t
Functions
bool hx711_scale_adaptor_init (hx711_scale_adaptor_t *const hxa, hx711_t *const hx)
scale_adaptor_t * hx711_scale_adaptor_get_base (hx711_scale_adaptor_t *const hxa)
bool hx711_scale_adaptor_get_value_timeout (scale_adaptor_t *const sa, int32_t *const value, const uint timeout)
bool hx711_scale_adaptor_get_value (scale_adaptor_t *const sa, int32_t *const value)
Function Documentation
hx711_scale_adaptor_get_base()
scale_adaptor_t* hx711_scale_adaptor_get_base (hx711_scale_adaptor_t *const hxa)
Definition at line 47 of file hx711_scale_adaptor.c.
{
         assert(hxa != NULL);
         return &hxa->_sa;
 }
References hx711_scale_adaptor_t::_sa.
hx711_scale_adaptor_get_value()
bool hx711_scale_adaptor_get_value (scale_adaptor_t *const sa, int32_t *const value)
Definition at line 66 of file hx711_scale_adaptor.c.
{
         assert(sa != NULL);
         assert(value != NULL);
         hx711_scale_adaptor_t* const hxa = scale_adaptor_get_data(sa);
         *value = hx711_get_value(hxa->_hx);
         return true;
 }
References hx711_scale_adaptor_t::_hx, and scale_adaptor_get_data().
Referenced by hx711_scale_adaptor_init().
hx711_scale_adaptor_get_value_timeout()
bool hx711_scale_adaptor_get_value_timeout (scale_adaptor_t *const sa, int32_t *const value, const uint timeout)
Definition at line 53 of file hx711_scale_adaptor.c.
{
         assert(sa != NULL);
         assert(value != NULL);
         hx711_scale_adaptor_t* const hxa = scale_adaptor_get_data(sa);
         return hx711_get_value_timeout(hxa->_hx, value, timeout);
 }
References hx711_scale_adaptor_t::_hx, and scale_adaptor_get_data().
Referenced by hx711_scale_adaptor_init().
hx711_scale_adaptor_init()
bool hx711_scale_adaptor_init (hx711_scale_adaptor_t *const hxa, hx711_t *const hx)
Definition at line 30 of file hx711_scale_adaptor.c.
{
         assert(hxa != NULL);
         assert(hx != NULL);
         hxa->_hx = hx;
         scale_adaptor_init(&hxa->_sa, hxa);
         hxa->_sa.get_value = hx711_scale_adaptor_get_value;
         hxa->_sa.get_value_timeout = hx711_scale_adaptor_get_value_timeout;
         return true;
 }
References hx711_scale_adaptor_t::_hx, hx711_scale_adaptor_t::_sa, scale_adaptor::get_value, scale_adaptor::get_value_timeout, hx711_scale_adaptor_get_value(), hx711_scale_adaptor_get_value_timeout(), and scale_adaptor_init().