pico-scale: include/mass.h File Reference
mass.h File Reference
#include <assert.h>
#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include "pico/types.h"
Data Structures
struct mass_t
Enumerations
enum mass_unit_t {
mass_ug = 0, mass_mg, mass_g, mass_kg,
mass_ton, mass_imp_ton, mass_us_ton, mass_st,
mass_lb, mass_oz
}
Functions
static const char *const mass_unit_to_string (const mass_unit_t u)
Returns a pointer to char with the textual representation of the unit.
static const double *const mass_unit_to_ratio (const mass_unit_t u)
Returns a pointer to a double with the number of micrograms per unit.
void mass_convert (const double *const fromAmount, double *const toAmount, const mass_unit_t fromUnit, const mass_unit_t toUnit)
Converts a floating point value from one unit to another.
static void mass_init (mass_t *const m, const mass_unit_t unit, const double val)
Initialises a mass_t with the given unit and value.
static void mass_get_value (const mass_t *const m, double *const val)
Sets val to the value representing the mass_t according to its unt.
static void mass_add (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res)
Add lhs to rhs and store result in res.
static void mass_sub (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res)
Substract rhs from lhs and store result in res.
static void mass_mul (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res)
Multiply lhs by rhs and store result in res.
static bool mass_div (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res)
Divide lhs by rhs and store result in res, returns false if rhs is 0.
static void mass_addeq (mass_t *const self, const mass_t *const rhs)
Add rhs to self.
static void mass_subeq (mass_t *const self, const mass_t *const rhs)
Subtract rhs from self.
static void mass_muleq (mass_t *const self, const mass_t *const rhs)
Multiply self by rhs.
static bool mass_diveq (mass_t *const self, const mass_t *const rhs)
Divide self by rhs, returns false if rhs is 0.
static bool mass_eq (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs equals rhs.
static bool mass_neq (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs does not equal rhs.
static bool mass_lt (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs is less than rhs.
static bool mass_gt (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs is greater than rhs.
static bool mass_lteq (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs is less than or equal to rhs.
static bool mass_gteq (const mass_t *const lhs, const mass_t *const rhs)
Returns true if lhs is greater than or equal to rhs.
int mass_to_string (const mass_t *const m, char *const buff)
Fills buff with the string representation of the mass_t. eg. "32.4762 mg".
Variables
static const double MASS_RATIOS []
static const char *const MASS_NAMES []
static const size_t MASS_TO_STRING_BUFF_SIZE = 64
Enumeration Type Documentation
mass_unit_t
enum mass_unit_t
Enum values are mapped to MASS_RATIOS and MASS_NAMES
Enumerator
mass_ug
mass_mg
mass_g
mass_kg
mass_ton
mass_imp_ton
mass_us_ton
mass_st
mass_lb
mass_oz
Definition at line 68 of file mass.h.
              {
     mass_ug = 0,
     mass_mg,
     mass_g,
     mass_kg,
     mass_ton,
     mass_imp_ton,
     mass_us_ton,
     mass_st,
     mass_lb,
     mass_oz
 } mass_unit_t;
Function Documentation
mass_add()
static void mass_add (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res) inline static
Add lhs to rhs and store result in res.
Parameters
lhs
rhs
res
Definition at line 163 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         assert(res != NULL);
         res->ug = lhs->ug + rhs->ug;
         res->unit = lhs->unit;
 }
References mass_t::ug, and mass_t::unit.
Referenced by mass_addeq().
mass_addeq()
static void mass_addeq (mass_t *const self, const mass_t *const rhs) inline static
Add rhs to self.
Parameters
self
rhs
Definition at line 254 of file mass.h.
{
         mass_add(self, rhs, self);
 }
References mass_add().
mass_convert()
void mass_convert (const double *const fromAmount, double *const toAmount, const mass_unit_t fromUnit, const mass_unit_t toUnit)
Converts a floating point value from one unit to another.
Parameters
fromAmount
toAmount
fromUnit
toUnit
Definition at line 54 of file mass.c.
{
         assert(fromAmount != NULL);
         assert(toAmount != NULL);
         if(fromUnit == toUnit) {
             *toAmount = *fromAmount;
         }
         else if(toUnit == mass_ug) {
             *toAmount = *fromAmount * *mass_unit_to_ratio(fromUnit);
         }
         else if(fromUnit == mass_ug) {
             *toAmount = *fromAmount / *mass_unit_to_ratio(toUnit);
         }
         else {
             mass_convert(fromAmount, toAmount, toUnit, mass_ug);
         }
 }
References mass_ug, and mass_unit_to_ratio().
Referenced by mass_get_value(), and mass_init().
mass_div()
static bool mass_div (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res) inline static
Divide lhs by rhs and store result in res, returns false if rhs is 0.
Parameters
lhs
rhs
res
Returns
true
false
Definition at line 228 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         assert(res != NULL);
         //if ~0; protect against div / 0
         if(fabs(rhs->ug) < DBL_EPSILON) {
             return false;
         }
         res->ug = lhs->ug / rhs->ug;
         res->unit = lhs->unit;
         return true;
 }
References mass_t::ug, and mass_t::unit.
Referenced by mass_diveq().
mass_diveq()
static bool mass_diveq (mass_t *const self, const mass_t *const rhs) inline static
Divide self by rhs, returns false if rhs is 0.
Parameters
self
rhs
Returns
true
false
Definition at line 292 of file mass.h.
{
         return mass_div(self, rhs, self);
 }
References mass_div().
mass_eq()
static bool mass_eq (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs equals rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 306 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         //if ~==; if approx ~0
         return fabs(lhs->ug - rhs->ug) < DBL_EPSILON;
 }
References mass_t::ug.
Referenced by mass_neq().
mass_get_value()
static void mass_get_value (const mass_t *const m, double *const val) inline static
Sets val to the value representing the mass_t according to its unt.
Parameters
m
val
Definition at line 145 of file mass.h.
{
         assert(m != NULL);
         assert(val != NULL);
         mass_convert(&m->ug, val, mass_ug, m->unit);
 }
References mass_convert(), mass_ug, mass_t::ug, and mass_t::unit.
Referenced by mass_to_string().
mass_gt()
static bool mass_gt (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs is greater than rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 364 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         return mass_lt(rhs, lhs);
 }
References mass_lt().
Referenced by mass_lteq().
mass_gteq()
static bool mass_gteq (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs is greater than or equal to rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 402 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         return !mass_lt(lhs, rhs);
 }
References mass_lt().
mass_init()
static void mass_init (mass_t *const m, const mass_unit_t unit, const double val) inline static
Initialises a mass_t with the given unit and value.
Parameters
m
unit
val
Definition at line 127 of file mass.h.
                       {
         assert(m != NULL);
         mass_convert(&val, &m->ug, unit, mass_ug);
         m->unit = unit;
 }
References mass_convert(), mass_ug, mass_t::ug, and mass_t::unit.
Referenced by scale_weight().
mass_lt()
static bool mass_lt (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs is less than rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 345 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         return lhs->ug < rhs->ug;
 }
References mass_t::ug.
Referenced by mass_gt(), and mass_gteq().
mass_lteq()
static bool mass_lteq (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs is less than or equal to rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 383 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         return !mass_gt(lhs, rhs);
 }
References mass_gt().
mass_mul()
static void mass_mul (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res) inline static
Multiply lhs by rhs and store result in res.
Parameters
lhs
rhs
res
Definition at line 205 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         assert(res != NULL);
         res->ug = lhs->ug * rhs->ug;
         res->unit = lhs->unit;
 }
References mass_t::ug, and mass_t::unit.
Referenced by mass_muleq().
mass_muleq()
static void mass_muleq (mass_t *const self, const mass_t *const rhs) inline static
Multiply self by rhs.
Parameters
self
rhs
Definition at line 278 of file mass.h.
{
         mass_mul(self, rhs, self);
 }
References mass_mul().
mass_neq()
static bool mass_neq (const mass_t *const lhs, const mass_t *const rhs) inline static
Returns true if lhs does not equal rhs.
Parameters
lhs
rhs
Returns
true
false
Definition at line 326 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         return !mass_eq(lhs, rhs);
 }
References mass_eq().
mass_sub()
static void mass_sub (const mass_t *const lhs, const mass_t *const rhs, mass_t *const res) inline static
Substract rhs from lhs and store result in res.
Parameters
lhs
rhs
res
Definition at line 184 of file mass.h.
{
         assert(lhs != NULL);
         assert(rhs != NULL);
         assert(res != NULL);
         res->ug = lhs->ug - rhs->ug;
         res->unit = lhs->unit;
 }
References mass_t::ug, and mass_t::unit.
Referenced by mass_subeq().
mass_subeq()
static void mass_subeq (mass_t *const self, const mass_t *const rhs) inline static
Subtract rhs from self.
Parameters
self
rhs
Definition at line 266 of file mass.h.
{
         mass_sub(self, rhs, self);
 }
References mass_sub().
mass_to_string()
int mass_to_string (const mass_t *const m, char *const buff)
Fills buff with the string representation of the mass_t. eg. "32.4762 mg".
Parameters
m
buff Must be at least MASS_TO_STRING_BUFF_SIZE in length
Returns
int Returns result of snprintf
Definition at line 26 of file mass.c.
                       {
         assert(m != NULL);
         assert(buff != NULL);
         double n; //value
         mass_get_value(m, &n);
         double i; //int part; discard
         const double f = fabs(modf(n, &i)); //frac part
         uint d = 0; //decimal count
         //if less than the epsilon, then it's ~0
         if(f >= DBL_EPSILON) {
             d = (uint)fmax(0, ceil(1 - log10(f)));
         }
         return snprintf(
             buff,
             MASS_TO_STRING_BUFF_SIZE,
             "%01.*f %s", //format
             d, //how many decimals
             n, //the value
             mass_unit_to_string(m->unit)); //suffix (ie. "kg")
 }
References mass_get_value(), MASS_TO_STRING_BUFF_SIZE, mass_unit_to_string(), and mass_t::unit.
mass_unit_to_ratio()
static const double* const mass_unit_to_ratio (const mass_unit_t u) inline static
Returns a pointer to a double with the number of micrograms per unit.
Parameters
u
Returns
const double* const
Definition at line 97 of file mass.h.
{
     return &MASS_RATIOS[(uint)u];
 }
References MASS_RATIOS.
Referenced by mass_convert().
mass_unit_to_string()
static const char* const mass_unit_to_string (const mass_unit_t u) inline static
Returns a pointer to char with the textual representation of the unit.
Parameters
u
Returns
const char* const
Definition at line 87 of file mass.h.
{
     return MASS_NAMES[(uint)u];
 }
References MASS_NAMES.
Referenced by mass_to_string().
Variable Documentation
MASS_NAMES
const char* const MASS_NAMES[] static
Initial value:
= {
    "g",
    "mg",
    "g",
    "kg",
    "ton",
    "ton (IMP)",
    "ton (US)",
    "st",
    "lb",
    "oz"
}
Definition at line 50 of file mass.h.
Referenced by mass_unit_to_string().
MASS_RATIOS
const double MASS_RATIOS[] static
Initial value:
= {
    1.0,
    1000.0,
    1000000.0,
    1000000000.0,
    1000000000000.0,
    1016046908800.0,
    907184740000.0,
    6350293180.0,
    453592370.0,
    28349523.125
}
Definition at line 37 of file mass.h.
Referenced by mass_unit_to_ratio().
MASS_TO_STRING_BUFF_SIZE
const size_t MASS_TO_STRING_BUFF_SIZE = 64 static
Definition at line 63 of file mass.h.
Referenced by mass_to_string().