pico-scale: src/mass.c File Reference
mass.c File Reference
#include "../include/mass.h"
#include <stdio.h>
Functions
int mass_to_string (const mass_t *const m, char *const buff)
Fills buff with the string representation of the mass_t. eg. "32.4762 mg".
void mass_convert (const double *const fromAmount, double *const toAmount, const mass_unit_t fromUnit, const mass_unit_t toUnit)
Converts a floating point value from one unit to another.
Function Documentation
mass_convert()
void mass_convert (const double *const fromAmount, double *const toAmount, const mass_unit_t fromUnit, const mass_unit_t toUnit)
Converts a floating point value from one unit to another.
Parameters
fromAmount
toAmount
fromUnit
toUnit
Definition at line 54 of file mass.c.
{
         assert(fromAmount != NULL);
         assert(toAmount != NULL);
         if(fromUnit == toUnit) {
             *toAmount = *fromAmount;
         }
         else if(toUnit == mass_ug) {
             *toAmount = *fromAmount * *mass_unit_to_ratio(fromUnit);
         }
         else if(fromUnit == mass_ug) {
             *toAmount = *fromAmount / *mass_unit_to_ratio(toUnit);
         }
         else {
             mass_convert(fromAmount, toAmount, toUnit, mass_ug);
         }
 }
References mass_ug, and mass_unit_to_ratio().
Referenced by mass_get_value(), and mass_init().
mass_to_string()
int mass_to_string (const mass_t *const m, char *const buff)
Fills buff with the string representation of the mass_t. eg. "32.4762 mg".
Parameters
m
buff Must be at least MASS_TO_STRING_BUFF_SIZE in length
Returns
int Returns result of snprintf
Definition at line 26 of file mass.c.
                       {
         assert(m != NULL);
         assert(buff != NULL);
         double n; //value
         mass_get_value(m, &n);
         double i; //int part; discard
         const double f = fabs(modf(n, &i)); //frac part
         uint d = 0; //decimal count
         //if less than the epsilon, then it's ~0
         if(f >= DBL_EPSILON) {
             d = (uint)fmax(0, ceil(1 - log10(f)));
         }
         return snprintf(
             buff,
             MASS_TO_STRING_BUFF_SIZE,
             "%01.*f %s", //format
             d, //how many decimals
             n, //the value
             mass_unit_to_string(m->unit)); //suffix (ie. "kg")
 }
References mass_get_value(), MASS_TO_STRING_BUFF_SIZE, mass_unit_to_string(), and mass_t::unit.