pico-scale: src/scale_adaptor.c File Reference
scale_adaptor.c File Reference
#include <assert.h>
#include <stddef.h>
#include "../include/scale_adaptor.h"
Functions
void scale_adaptor_init (scale_adaptor_t *const sa, void *data)
void * scale_adaptor_get_data (scale_adaptor_t *const sa)
Function Documentation
scale_adaptor_get_data()
void* scale_adaptor_get_data (scale_adaptor_t *const sa)
Definition at line 34 of file scale_adaptor.c.
{
         assert(sa != NULL);
         return sa->_data;
 }
References scale_adaptor::_data.
Referenced by hx711_scale_adaptor_get_value(), and hx711_scale_adaptor_get_value_timeout().
scale_adaptor_init()
void scale_adaptor_init (scale_adaptor_t *const sa, void * data)
Definition at line 27 of file scale_adaptor.c.
                 {
         assert(sa != NULL);
         sa->_data = data;
 }
References scale_adaptor::_data.
Referenced by hx711_scale_adaptor_init().