pico-scale: include/scale_adaptor.h File Reference
scale_adaptor.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include "pico/types.h"
Data Structures
struct scale_adaptor
Typedefs
typedef struct scale_adaptor scale_adaptor_t
Functions
bool scale_adaptor_init (scale_adaptor_t *const sa, void *data)
void * scale_adaptor_get_data (scale_adaptor_t *const sa)
Typedef Documentation
scale_adaptor_t
typedef struct scale_adaptor scale_adaptor_t
Function Documentation
scale_adaptor_get_data()
void* scale_adaptor_get_data (scale_adaptor_t *const sa)
Definition at line 35 of file scale_adaptor.c.
{
         assert(sa != NULL);
         return sa->_data;
 }
References scale_adaptor::_data.
Referenced by hx711_scale_adaptor_get_value(), and hx711_scale_adaptor_get_value_timeout().
scale_adaptor_init()
bool scale_adaptor_init (scale_adaptor_t *const sa, void * data)
Definition at line 27 of file scale_adaptor.c.
                 {
         assert(sa != NULL);
         sa->_data = data;
         return true;
 }
References scale_adaptor::_data.
Referenced by hx711_scale_adaptor_init().