pico-scale: src/scale.c File Reference
scale.c File Reference
#include <assert.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include "pico/time.h"
#include "../include/scale.h"
#include "../include/scale_adaptor.h"
#include "../include/util.h"
Functions
void scale_init (scale_t *const sc, scale_adaptor_t *const adaptor, const mass_unit_t unit, const int32_t ref_unit, const int32_t offset)
Initialise the scale with a hx711_t.
bool scale_normalise (const scale_t *const sc, const double *const raw, double *const normalised)
Adjusts a raw value to a normalised value according to the scale's reference unit and offset. Returns true if the operation succeeded.
bool scale_get_values_samples (scale_t *const sc, int32_t **const arr, const size_t len)
Fills arr with len number of samples from the scale. Returns true if the operation succeeded.
bool scale_get_values_timeout (scale_t *const sc, int32_t **const arr, size_t *const len, const uint timeout)
Fills arr with as many number of samples as possible up to the timeout. Returns true if the operation succeeded.
bool scale_read (scale_t *const sc, double *const val, const scale_options_t *const opt)
Obtains a value from the scale according to the given options. Returns true if the operation succeeded.
bool scale_zero (scale_t *const sc, const scale_options_t *const opt)
Zeros the scale (tare) by adjusting its offset from 0 according to the given options. Returns true if the operation succeeded.
bool scale_weight (scale_t *const sc, mass_t *const m, const scale_options_t *const opt)
Obtains a weight from the scale according to the given options. Returns true if the operation succeeded.
Function Documentation
scale_get_values_samples()
bool scale_get_values_samples (scale_t *const sc, int32_t **const arr, const size_t len)
Fills arr with len number of samples from the scale. Returns true if the operation succeeded.
Parameters
sc
arr
len
Returns
true
false
Definition at line 69 of file scale.c.
                       {
         assert(sc != NULL);
         assert(sc->_adaptor != NULL);
         assert(arr != NULL);
         //if the allocation fails, return false
         if((*arr = malloc(len * sizeof(int32_t))) == NULL) {
             return false;
         }
         for(size_t i = 0; i < len; ++i) {
             sc->_adaptor->get_value(
                 sc->_adaptor,
                 &(*arr)[i]);
         }
         return true;
 }
References scale_t::_adaptor, and scale_adaptor::get_value.
Referenced by scale_read().
scale_get_values_timeout()
bool scale_get_values_timeout (scale_t *const sc, int32_t **const arr, size_t *const len, const uint timeout)
Fills arr with as many number of samples as possible up to the timeout. Returns true if the operation succeeded.
Parameters
sc
arr
len Will be to the number of samples obtained
timeout Microseconds
Returns
true
false
By default, allocate memory for 80 ints. The reasoning for this is as follows:
A "scale" application is likely to need to update at a rate of once per second or less. So the size of the allocation can be the same size as the HX711 samples per second.
The HX711 has two rates (excluding when using an external crystal): 10 and 80 samples per second. But this function has no information about the rate in use. If the actual rate is 10 and the allocated size is for 10, then few if any reallocations should occur. But if the actual rate is 80 and the allocated size is for 10, at least 8 reallocations would occur. On the other hand, if the actual rate is 10 and the allocated size is for 80 ints, no reallocations should occur. The obvious tradeoff is the excess memory.
Definition at line 93 of file scale.c.
{
         assert(sc != NULL);
         assert(sc->_adaptor != NULL);
         assert(arr != NULL);
         assert(len != NULL);
         int32_t val; //temporary value from the adaptor
         int32_t* memblock; //ptr to the memblock
         size_t elemCount; //number of elements in the block
         //elemCount = hx711_get_rate_sps(hx711_rate_80);
         //if((*arr = malloc(elemCount * sizeof(int32_t))) == NULL) {
         //    return false;
         //}
         *len = 0;
         while(sc->_adaptor->get_value_timeout(sc->_adaptor, &val, timeout)) {
             //new value available, so increase the counter
             //this is the actual number of values obtained
             ++(*len);
             //check if a reallocation is needed
             if(*len > elemCount) {
                 //when a reallocation is needed, double the space
                 elemCount = elemCount * 2;
                 memblock = realloc(
                     *arr,
                     elemCount * sizeof(int32_t));
                 //if memory allocation fails, return false
                 //existing *arr will still be allocated
                 //but will be freed in caller function
                 if(memblock == NULL) {
                     return false;
                 }
                 //move pointer of new block to *arr
                 *arr = memblock;
             }
             //store the value in the array
             (*arr)[(*len) - 1] = val;
         }
         //no errors occurred, so return true
         return true;
 }
References scale_t::_adaptor, and scale_adaptor::get_value_timeout.
Referenced by scale_read().
scale_init()
void scale_init (scale_t *const sc, scale_adaptor_t *const adaptor, const mass_unit_t unit, const int32_t ref_unit, const int32_t offset)
Initialise the scale with a hx711_t.
Parameters
sc Pointer to scale_t
hx Pointer to hx711_t
unit The mass_unit_t to output mass_t's in
ref_unit The reference unit to use (see: calibration)
offset The offset from 0 (see: calibration)
Definition at line 32 of file scale.c.
{
         assert(sc != NULL);
         assert(adaptor != NULL);
         assert(ref_unit != 0);
         sc->_adaptor = adaptor;
         sc->unit = unit;
         sc->ref_unit = ref_unit;
         sc->offset = offset;
 }
References scale_t::_adaptor, scale_t::offset, scale_t::ref_unit, and scale_t::unit.
scale_normalise()
bool scale_normalise (const scale_t *const sc, const double *const raw, double *const normalised)
Adjusts a raw value to a normalised value according to the scale's reference unit and offset. Returns true if the operation succeeded.
Parameters
sc
raw
normalised
Returns
true
false
Definition at line 50 of file scale.c.
{
         assert(sc != NULL);
         assert(raw != NULL);
         assert(normalised != NULL);
         //protect against div / 0
         if(sc->ref_unit == 0) {
             return false;
         }
         *normalised = (*raw - sc->offset) / sc->ref_unit;
         return true;
 }
References scale_t::offset, and scale_t::ref_unit.
Referenced by scale_weight().
scale_read()
bool scale_read (scale_t *const sc, double *const val, const scale_options_t *const opt)
Obtains a value from the scale according to the given options. Returns true if the operation succeeded.
Parameters
sc
val
opt
Returns
true
false
Definition at line 174 of file scale.c.
{
         assert(sc != NULL);
         assert(val != NULL);
         assert(opt != NULL);
         int32_t* arr = NULL;
         size_t len = 0;
         bool ok = false; //assume error
         switch(opt->strat) {
         case strategy_type_time:
             ok = scale_get_values_timeout(
                 sc,
                 &arr,
                 &len,
                 opt->timeout);
             break;
         case strategy_type_samples:
         default:
             len = opt->samples;
             ok = scale_get_values_samples(
                 sc,
                 &arr,
                 len);
             break;
         }
         //if an error occurred or no samples obtained
         //deallocate any memory and then return false
         if(!ok || len == 0) {
             free(arr);
             return false;
         }
         switch(opt->read) {
         case read_type_average:
             util_average(arr, len, val);
             break;
         case read_type_median:
         default:
             util_median(arr, len, val);
             break;
         }
         //at this point, statistical func is done
         //so deallocate and return true
         free(arr);
         return true;
 }
References scale_options_t::read, read_type_average, read_type_median, scale_options_t::samples, scale_get_values_samples(), scale_get_values_timeout(), scale_options_t::strat, strategy_type_samples, strategy_type_time, scale_options_t::timeout, util_average(), and util_median().
Referenced by scale_weight(), and scale_zero().
scale_weight()
bool scale_weight (scale_t *const sc, mass_t *const m, const scale_options_t *const opt)
Obtains a weight from the scale according to the given options. Returns true if the operation succeeded.
Parameters
sc
m
opt
Returns
true
false
Definition at line 256 of file scale.c.
{
         assert(sc != NULL);
         assert(m != NULL);
         assert(opt != NULL);
         double val;
         //if the read fails, return false
         if(!scale_read(sc, &val, opt)) {
             return false;
         }
         //if normalising the value fails, return false
         if(!scale_normalise(sc, &val, &val)) {
             return false;
         }
         mass_init(m, sc->unit, val);
         return true;
 }
References mass_init(), scale_normalise(), scale_read(), and scale_t::unit.
scale_zero()
bool scale_zero (scale_t *const sc, const scale_options_t *const opt)
Zeros the scale (tare) by adjusting its offset from 0 according to the given options. Returns true if the operation succeeded.
Parameters
sc
opt
Returns
true
false
Definition at line 231 of file scale.c.
{
         assert(sc != NULL);
         assert(opt != NULL);
         double val;
         const int32_t refBackup = sc->ref_unit;
         bool ok = false;
         sc->ref_unit = 1;
         if((ok = scale_read(sc, &val, opt))) {
             //only change the offset if the read
             //succeeded
             sc->offset = (int32_t)round(val);
         }
         sc->ref_unit = refBackup;
         return ok;
 }
References scale_t::offset, scale_t::ref_unit, and scale_read().