pico-scale: scale_adaptor Struct Reference
scale_adaptor Struct Reference
#include <scale_adaptor.h>
Data Fields
void * _data
Arbitrary user data.
bool(* get_value)(struct scale_adaptor *const sa, int32_t *const value)
Function pointer to function.
bool(* get_value_timeout)(struct scale_adaptor *const sa, int32_t *const value, const uint timeout)
Function pointer to function.
Detailed Description
Definition at line 34 of file scale_adaptor.h.
Field Documentation
_data
void* scale_adaptor::_data
Arbitrary user data.
Definition at line 39 of file scale_adaptor.h.
Referenced by scale_adaptor_get_data(), and scale_adaptor_init().
get_value
bool(* scale_adaptor::get_value) (struct scale_adaptor *const sa, int32_t *const value)
Function pointer to function.
Parameters
sa pointer to scale adaptor
value value to be set
Definition at line 46 of file scale_adaptor.h.
Referenced by hx711_scale_adaptor_init(), and scale_get_values_samples().
get_value_timeout
bool(* scale_adaptor::get_value_timeout) (struct scale_adaptor *const sa, int32_t *const value, const uint timeout)
Function pointer to function.
Parameters
sa pointer to scale adaptor
value value to be set
timeout timeout in microseconds
Definition at line 56 of file scale_adaptor.h.
Referenced by hx711_scale_adaptor_init(), and scale_get_values_timeout().
The documentation for this struct was generated from the following file:
include/scale_adaptor.h