pico-scale: include/util.h File Reference
util.h File Reference
#include <assert.h>
#include <stddef.h>
#include <stdint.h>
Functions
void util_average (const int32_t *const arr, const size_t len, double *const avg)
Calculates the average value from an array of signed 32-bit integers.
void util_median (int32_t *const arr, const size_t len, double *const med)
Calculates the median value from an array of signed 32-bit integers.
static int util__median_compare_func (const void *a, const void *b)
Function Documentation
util__median_compare_func()
static int util__median_compare_func (const void * a, const void * b) inline static
Definition at line 58 of file util.h.
                    {
         assert(a != NULL);
         assert(b != NULL);
         const int32_t* restrict const pA = (const int32_t* const)a;
         const int32_t* restrict const pB = (const int32_t* const)b;
         //https://stackoverflow.com/a/10996555/570787
         return (*pA < *pB) ? -1 : (*pA > *pB);
 }
Referenced by util_median().
util_average()
void util_average (const int32_t *const arr, const size_t len, double *const avg)
Calculates the average value from an array of signed 32-bit integers.
Parameters
arr array of values
len number of values in the array
avg
Definition at line 26 of file util.c.
{
         assert(arr != NULL);
         assert(len > 0);
         assert(avg != NULL);
         long long int total = 0;
         for(size_t i = 0; i < len; ++i) {
             total += arr[i];
         }
         *avg = (double)total / len;
 }
Referenced by scale_read().
util_median()
void util_median (int32_t *const arr, const size_t len, double *const med)
Calculates the median value from an array of signed 32-bit integers.
Parameters
arr array of values
len number of values in the array
med
If the number of elements is even, the median is the average of the middle two elements. Otherwise it is the middle element.
Definition at line 45 of file util.c.
{
         assert(arr != NULL);
         assert(len > 0);
         assert(med != NULL);
         qsort(
             arr,
             len,
             sizeof(int32_t),
             util__median_compare_func);
         if(len % 2 == 0) {
             *med = (arr[(len / 2) - 1] + arr[len / 2]) / 2.0;
         }
         else {
             *med = (double)arr[(len / 2) + 1];
         }
 }
References util__median_compare_func().
Referenced by scale_read().